apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: besu-metrics
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - blockchain
  selector:
    matchLabels:
      app.kubernetes.io/component: besu
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
