apiVersion: v1
kind: Secret
metadata:
  name: rpc-node-secret
  namespace: blockchain
type: Opaque
data:
  key: ODhjYTgxNDk5NTkzNTI1MTY2MzJjZTZmYTgyNjBiYzhmMjZhYzI2OGNiZDZjOWRkMGQ3MzA5ZjRmZmE0ZWEzMA==
