apiVersion: v1
kind: Secret
metadata:
  name: validator1-secret
  namespace: blockchain
type: Opaque
data:
  key: YWY3OTFlZDgzZjdjMjcyYmEwYWQ1MjE5OGY4ZmYyNTQ3ZmVjOTc1NGI5ODNhMGUwYjBjZjhlNDBkZjQ2NjM4NAo=

