apiVersion: v1
kind: Secret
metadata:
  name: validator3-secret
  namespace: blockchain
type: Opaque
data:
  key: NzYwOWQxNzM0MjA5NzYxODZmM2JhNDA3OTAxZjg5NjE1NzlkODMzM2ZmYTRhMTM2NzJmNjM1MTUyZTI3ZTdjOQo=
