apiVersion: v1
kind: Secret
metadata:
  name: validator2-secret
  namespace: blockchain
type: Opaque
data:
  key: NDhmYWE0MGI3YzI1MDBhZTI5N2QxZTY3MWExYWYzNjZmNTk1YTYzMWY4ZWQ2YWZlYzFmY2VjNzQ3Y2Y5ZDg3Ywo=
