apiVersion: v1
kind: Secret
metadata:
  name: validator4-secret
  namespace: blockchain
type: Opaque
data:
  key: NWVkMGViNmEzYmI2MDBiZWZiYWRjOThjNGVmMzMxYmJjMTc2YjM1OTg4MWUxNjBiNjc5NmYyZWU3Y2MyYmVjOQ==
