apiVersion: v1
kind: Secret
metadata:
  name: validator5-secret
  namespace: blockchain
type: Opaque
data:
  key: M2FiODk2YzNlMWViZmI1M2E0Y2VjYzJmMjNjZjFlMTA0OTk4NGEyYTg3YmFiMGVkZTBiN2I3NTBiMWRhMWRkYw==
