apiVersion: v1
kind: Secret
metadata:
  name: validator1-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  key: {{ .Values.keys.validator1 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: validator2-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  key: {{ .Values.keys.validator2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: validator3-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  key: {{ .Values.keys.validator3 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: validator4-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  key: {{ .Values.keys.validator4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: validator5-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  key: {{ .Values.keys.validator5 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rpc-node-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  key: {{ .Values.rpc.key }}