apiVersion: v1
kind: Service
metadata:
  name: validator1
  namespace: blockchain
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: validator1
  ports:
    - name: p2p
      port: 30303
    - name: rpc
      port: 8545
    - name: metrics
      port: 9545
---
apiVersion: v1
kind: Service
metadata:
  name: validator2
  namespace: blockchain
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: validator2
  ports:
    - name: p2p
      port: 30303
    - name: rpc
      port: 8545
    - name: metrics
      port: 9545
---
apiVersion: v1
kind: Service
metadata:
  name: validator3
  namespace: blockchain
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: validator3
  ports:
    - name: p2p
      port: 30303
    - name: rpc
      port: 8545
    - name: metrics
      port: 9545
---
apiVersion: v1
kind: Service
metadata:
  name: validator4
  namespace: blockchain
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: validator4
  ports:
    - name: p2p
      port: 30303
    - name: rpc
      port: 8545
    - name: metrics
      port: 9545
---
apiVersion: v1
kind: Service
metadata:
  name: validator5
  namespace: blockchain
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: validator5
  ports:
    - name: p2p
      port: 30303
    - name: rpc
      port: 8545
    - name: metrics
      port: 9545
