apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: validator2
  namespace: blockchain
spec:
  serviceName: validator2
  replicas: 1
  selector:
    matchLabels:
      app: validator2
  template:
    metadata:
      labels:
        app: validator2
    spec:
      containers:
        - name: besu
          image: hyperledger/besu:25.8.0
          command:
            - /bin/sh
            - /scripts/besu-startup.sh
          ports:
            - containerPort: 30303
            - containerPort: 8545
            - containerPort: 9545
          volumeMounts:
            - name: data
              mountPath: /data
            - name: genesis
              mountPath: /config
            - name: keys
              mountPath: /keys
            - name: startup-script
              mountPath: /scripts
      volumes:
        - name: genesis
          configMap:
            name: besu-genesis
        - name: keys
          secret:
            secretName: validator2-secret
        - name: startup-script
          configMap:
            name: besu-startup-script
            defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: blockchain-local
      resources:
        requests:
          storage: 90Gi
